# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
#    parameter_name: value
    fin: 20

services:
#    service_name:
#        class: AppBundle\Directory\ClassName
#        arguments: ["@another_service_name", "plain_value", "%parameter_name%"]
    vaysse.extrait:
        class: AppBundle\Tools\Extrait
        arguments: ["@session", "...", "%fin%"]
        tags:
            - {name: twig.extension}
    app.maintenance:
        class: AppBundle\Listener\MaintenanceListener
        arguments: [false,"@templating"]
        tags:
            - {name: kernel.event_listener,event: kernel.response, method: onKernelResponse}    
            
