<?php

namespace Kevin\CatalogueBundle\Repository;



/**
 * ArticleRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ArticleRepository extends \Doctrine\ORM\EntityRepository
{
	public function getArticlesByCat($categorie){
	$qb=$this->createQueryBuilder("a")->leftJoin('a.categories','c')->addSelect('c')
	->where('c=:cat')->setParameter('cat', $categorie)
	->orderBy('a.prix','DESC');
	$query=$qb->getQuery();
	return $query->getResult();
	}
	
	public function getArticleById($articleid){
		$qb=$this->createQueryBuilder("a")->leftJoin('a.image','i')->addSelect('i')
		->where('a.id=:id')->setParameter('id', $articleid);
		$query=$qb->getQuery();
		return $query->getResult();
	}
	
	}
